<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <DocumentationFile>API.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="FluentAssertions" Version="8.2.0" />
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="Unity" Version="5.11.10" />
    <PackageReference Include="Unity.ServiceLocation" Version="5.11.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catharsis.Repository.Core\Catharsis.Repository.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Catharsis.Commons">
      <HintPath>..\..\lib\net9.0\Catharsis.Commons.dll</HintPath>
    </Reference>
    <Reference Include="Catharsis.Extensions">
      <HintPath>..\..\lib\net9.0\Catharsis.Extensions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
